RubiMonti/arquitectura_software

CMakeLists.txt, package.xml
Signed-off-by: marioesteban11 <marioesteban00@gmail.com>
=> CmakeList + package.xml

bumper/CMakeLists.txt, bumper/package.xml, bumper/src/bumper_robot.cpp
Esta es una primera versión sin código en la que nos vamos a basar para hacer el proyecto.
=> estructura proyecto

CMakeLists.txt
Cambios en CMake list, funciona?
=> Marioesteban

bumper/CMakeLists.txt, bumper/src/bumper_robot.cpp
En este fichero se ha programado lo elemental del bumper. Va todo recto hasta que se choca, entonces se queda parado.
=> Bumper que se mueve hasta que se choca

bumper/src/bumper_new_version.cpp
Hi @RubiMonti 
Esta es una nueva versión en la que el robot consigue pararse ante un obstáculo pero no consigue avanzar una vez que se ha parado
=> Nueva version

bumper/CMakeLists.txt, bumper/src/bumper_new_version.cpp
He pasado los tests al fichero de la nueva versión del bumper.
=> Test pasado a la nueva version

bumper/src/bumper_robot.cpp
=> Cambios en la correccion de clase

laser_go/CMakeLists.txt, laser_go/package.xml
Estos son los ficheros CMakeLists y package.xml
=> CMakeLists y package hechos

laser_go/src/laser_robot.cpp
Falta por mejorar la máquina de estados para que gire dependiendo del lado en que se choca
=> Añadido el programa del laser, funciona exceptuando la izquierda

laser_go/src/laser_robot.cpp
He cambiado las fórmulas de los grados para que resulte más intuitivo el uso de los ángulos
=> Arreglado el laser. Funciona en los tres ángulos solicitados.

laser_go/src/laser_robot.cpp
He hecho varios cambios en la máquina de estados y ya cumplen las funciones especificadas. Además, los markers ahora sí que cambian de color dependiendo de cual ha sido "pulsado".
=> Avances en la máquina de estados y markers funcionan correctamente

laser_go/CMakeLists.txt, laser_go/include/laser_go/LaserRobot.h, laser_go/package.xml, laser_go/src/laser_go/LaserRobot.cpp, laser_go/src/laser_robot_executable.cpp
He dividido el fichero en .cpp, .h y el ejecutable.
=> Programa dividido en ficheros .cpp, .h y ejecutable

laser_go/include/laser_go/LaserRobot.h, laser_go/src/laser_go/LaserRobot.cpp
Había algunos errores que no me saltaron en tiempo de compilación(ya he solucionado ese problema), así que los subo otra vez modificados, solucionando esos errores.
=> Ficheros modificados, solucionando algunos errores

laser_go/src/laser_go/LaserRobot.cpp
He cambiado algunas velocidades y distancias para un comportamiento más natural del robot
=> Ajustadas las distancias y las velocidades 

ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/launcher/ball_and_goal.launch, ball_and_goal/src/ball_and_goal/BallAndGoalBica.cpp, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/find_ball_node.cpp
=> Compiles but doesnt work yet.

ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
=> Final version before first deadline.

ball_and_goal/CMakeLists.txt, ball_and_goal/include/ball_and_goal/FindBall.h, ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/include/ball_and_goal/FindYellowGoal.h, ball_and_goal/src/ball_and_goal/BallAndGoalBica.cpp, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp, ball_and_goal/src/ball_and_goal/Turn.cpp, ball_and_goal/src/ball_and_goal_node.cpp, ball_and_goal/src/find_ball_node.cpp, ball_and_goal/src/find_blue_goal_node.cpp, ball_and_goal/src/find_yellow_goal_node.cpp, ball_and_goal/src/turn_node.cpp
=> Last minute changes. Roslint checked

ball_and_goal/CMakeLists.txt, ball_and_goal/include/ball_and_goal/BallAndGoalBica.h, ball_and_goal/include/ball_and_goal/FindBall.h, ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/include/ball_and_goal/FindYellowGoal.h, ball_and_goal/include/ball_and_goal/Turn.h
=> Last minute changes. Roslint checked all

ball_and_goal/CMakeLists.txt, ball_and_goal/include/ball_and_goal/BallAndGoalBica.h, ball_and_goal/launcher/ball_and_goal.launch, ball_and_goal/src/ball_and_goal/BallAndGoalBica.cpp, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
=> Updates after first deadline. Works without tf

ball_and_goal/CMakeLists.txt
The files where we used OpenCv did not let us compile (just Mario and me), so I have made some changes so that the project could be compiled and executed by all of us.
=> Changes made in CMake file so that the opencv lines can compile

ball_and_goal/CMakeLists.txt, ball_and_goal/include/ball_and_goal/FindBall.h, ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/include/ball_and_goal/FindYellowGoal.h, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
The robot is able to reach the ball without turning so much and put the transform.
=> Advances in transforms

ball_and_goal/include/ball_and_goal/BallAndGoalBica.h, ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/include/ball_and_goal/FindYellowGoal.h, ball_and_goal/src/ball_and_goal/BallAndGoalBica.cpp, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
=> Updated tfs but still disappearing.

ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/include/ball_and_goal/FindYellowGoal.h, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
=> Added laser scan. Tfs still not working

ball_and_goal/include/ball_and_goal/FindBall.h, ball_and_goal/include/ball_and_goal/FindBlueGoal.h, ball_and_goal/include/ball_and_goal/FindYellowGoal.h, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
Static transforms used but we have to adjust the angle.
=> Transforms working but have to adjust angle

ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
This version of the proyect works correctly.
=> Final version, it works fine

ball_and_goal/include/ball_and_goal/BallAndGoalBica.h, ball_and_goal/src/ball_and_goal/BallAndGoalBica.cpp, ball_and_goal/src/ball_and_goal/FindBall.cpp, ball_and_goal/src/ball_and_goal/FindBlueGoal.cpp, ball_and_goal/src/ball_and_goal/FindYellowGoal.cpp
Final version just adjusted velocities.
=> Final version changing velocities

hospital_navigation/CMakeLists.txt, hospital_navigation/maps/map.yaml, hospital_navigation/package.xml, hospital_navigation/param/costmap_common_params.yaml, hospital_navigation/param/dummy.yaml, hospital_navigation/param/dwa_local_planner_params.yaml, hospital_navigation/param/global_costmap_params.yaml, hospital_navigation/param/global_planner_params.yaml, hospital_navigation/param/local_costmap_params.yaml, hospital_navigation/param/move_base_params.yaml, hospital_navigation/param/navfn_global_planner_params.yaml, hospital_navigation/param/smoother.yaml, hospital_navigation/src/navigation.cpp
I have created the package for the new project and the map for the hospital world.
=> New package done for practise 4 and map(hospital) created

hospital_navigation/CMakeLists.txt, hospital_navigation/launch/navigation.launch, hospital_navigation/maps/map.yaml, hospital_navigation/package.xml, hospital_navigation/param/costmap_common_params.yaml, hospital_navigation/param/dummy.yaml, hospital_navigation/param/dwa_local_planner_params.yaml, hospital_navigation/param/global_costmap_params.yaml, hospital_navigation/param/global_planner_params.yaml, hospital_navigation/param/local_costmap_params.yaml, hospital_navigation/param/move_base_params.yaml, hospital_navigation/param/navfn_global_planner_params.yaml, hospital_navigation/param/smoother.yaml, hospital_navigation/src/navigation.cpp
=> Made some changes in the main node but still not working

hospital_navigation/CMakeLists.txt, hospital_navigation/launch/localization.launch, hospital_navigation/src/navigation.cpp, hospital_navigation/src/navigation_kobuki.cpp, hospital_navigation/src/publish_points.cpp
Publication of coordinates made but doesn't work properly.
=> Advances made in the publication of waypoints

hospital_navigation/CMakeLists.txt, hospital_navigation/src/navigation_once.cpp
I tried the input of arguments and it works, now we have to associate each input with the coordinates.
=> Made some advances in part 1. Missing coordinates

hospital_navigation/CMakeLists.txt, hospital_navigation/launch/includes/amcl.launch.xml, hospital_navigation/launch/includes/gmapping.launch.xml, hospital_navigation/launch/includes/move_base.launch.xml, hospital_navigation/launch/includes/safety_controller.launch.xml, hospital_navigation/launch/includes/velocity_smoother.launch.xml, hospital_navigation/launch/localization.launch, hospital_navigation/launch/navigation.launch, hospital_navigation/launch/octomap_mapping.launch, hospital_navigation/launch/slam_mapping.launch, hospital_navigation/launch/static_map.launch, hospital_navigation/param/costmap_common_params.yaml, hospital_navigation/param/dwa_local_planner_params.yaml, hospital_navigation/src/navigation_once.cpp, hospital_navigation/src/navigation_secuencial.cpp
Everything works fine but robot has problems with walls.
=> Everything works but sometimes the robot has problems with walls

hospital_navigation/src/navigation_once.cpp, hospital_navigation/src/navigation_secuencial.cpp
Files organised with functions.
=> Files organised

hospital_navigation/CMakeLists.txt, hospital_navigation/src/navigation_once.cpp, hospital_navigation/src/navigation_secuencial.cpp
=> Roslint checked

hospital_navigation/src/navigation_secuencial.cpp
=> Everything works perfectly

hospital_navigation/config/points_params.yaml, hospital_navigation/launch/params_config.launch
=> Added videos of the execution of each part

hospital_navigation/src/navigation_once.cpp, hospital_navigation/src/navigation_secuencial.cpp
=> Roslint made

behaviour_hospital/src/node_rgbd_distance.cpp
Robot can go to a place given by param.
=> Robot able to go to a place

behavior_hospital/CMakeLists.txt, behavior_hospital/package.xml, behavior_hospital/src/behavior_hospital/Behavior_hospital_impl.cpp, behavior_hospital/src/behavior_hospital/Find_object.cpp, behavior_hospital/src/behavior_hospital/Go_goal.cpp, behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
Objects can be detected using the id with darknet.
=> Object detected with darknet

behavior_hospital/src/darknet_node.cpp
=> Object detected using class and publishing detection

behavior_hospital/src/darknet_node.cpp
=> Added input of an object

behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Advances in the publication of points

behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Obtained 3d coordinate from desired object

behavior_hospital/launch/dark_config.launch, behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
Able to get the 2d object points.
=> Getting 2d points of the object

behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Now it should place the tf in the right spot

behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
This version works correctly, no tests passed.
=> It places the tf correctly

behavior_hospital/CMakeLists.txt
Videos showing that everything works correctly.
=> Videos showing that everything works

behavior_hospital/CMakeLists.txt, behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Tests passed

behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
I have made modifications to the project, but it still does not work properly.
=> Made some modifications to the first part of the project

behavior_hospital/CMakeLists.txt, behavior_hospital/behavior_trees_xml/hospital_tree.xml, behavior_hospital/include/behavior_hospital/darknet_detector.h, behavior_hospital/include/behavior_hospital/go_room.h, behavior_hospital/package.xml, behavior_hospital/src/behavior_hospital/darknet_detector.cpp, behavior_hospital/src/behavior_hospital/go_room.cpp, behavior_hospital/src/behavior_hospital/rgbd_distance.cpp, behavior_hospital/src/behavior_hospital_node.cpp
=> Made the actual project with behavior trees

behavior_hospital/behavior_trees_xml/hospital_tree.xml, behavior_hospital/include/behavior_hospital/darknet_detector.h, behavior_hospital/include/behavior_hospital/go_room.h, behavior_hospital/src/behavior_hospital/go_room.cpp, behavior_hospital/src/behavior_hospital_node.cpp
Some advances in blackboard although doesn't compile.
=> Advances in blackboard

behavior_hospital/behavior_trees_xml/hospital_tree.xml, behavior_hospital/config/rviz_config.rviz, behavior_hospital/include/behavior_hospital/go_room.h, behavior_hospital/launch/Behavior_hospital.launch, behavior_hospital/launch/dark_config.launch, behavior_hospital/launch/params_config.launch, behavior_hospital/src/behavior_hospital/go_room.cpp, behavior_hospital/src/behavior_hospital/rgbd_distance.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Made some advances in transforms

behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Publication of transforms done

behavior_hospital/behavior_trees_xml/hospital_tree.xml, behavior_hospital/include/behavior_hospital/darknet_detector.h, behavior_hospital/include/behavior_hospital/go_room.h, behavior_hospital/src/behavior_hospital/darknet_detector.cpp, behavior_hospital/src/behavior_hospital/go_room.cpp, behavior_hospital/src/behavior_hospital_node.cpp, behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
Robot face the object but doesnt go forward.
=> Robot face the object but doesnt go forward

behavior_hospital/CMakeLists.txt, behavior_hospital/behavior_trees_xml/hospital_tree.xml, behavior_hospital/include/behavior_hospital/find_approach.h, behavior_hospital/src/behavior_hospital/find_approach.cpp, behavior_hospital/src/behavior_hospital_node.cpp
Signed-off-by: marioesteban11 <marioesteban00@gmail.com>
=> Changes that compiles on aprroach movement

behavior_hospital/include/behavior_hospital/find_approach.h, behavior_hospital/src/behavior_hospital/find_approach.cpp, behavior_hospital/src/behavior_hospital/go_room.cpp, behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
=> Proyect done with success

behavior_hospital/src/behavior_hospital/find_approach.cpp, behavior_hospital/src/behavior_hospital/go_room.cpp, behavior_hospital/src/behavior_hospital_node.cpp, behavior_hospital/src/darknet_node.cpp, behavior_hospital/src/node_rgbd_distance.cpp
Signed-off-by: marioesteban11 <marioesteban00@gmail.com>
=> Roslint passed and a new video uploaded

behavior_hospital/CMakeLists.txt, behavior_hospital/behavior_trees_xml/hospital_tree.xml, behavior_hospital/include/behavior_hospital/is_room.h, behavior_hospital/src/behavior_hospital/find_approach.cpp, behavior_hospital/src/behavior_hospital/is_room.cpp
=> Made some changes mentioned during correction
